---
title: "Penguin Analysis"
author: "Daniel Chen"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    toc: true
    toc_depth: 2
  
  
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction
```{r}
library(palmerpenguins)
library(knitr)
library(here)

print(getwd())

source(here("R/predict.R"))

kable(head(penguins))
```

## Data Wrangling
```{r}
penguins <- penguins %>%
  drop_na() %>% # TODO: make sure you clean this at the top
  mutate(my_predict = map2_chr(bill_length_mm, flipper_length_mm, classify_penguin))
```

```{r, message=FALSE}
library(tidyverse)
```

## EDA
```{r, message=FALSE, warning=FALSE, fig.alt="This is for a screen reader and this is a figure of the bill_length_mm on the x axis, and the fillter_lenth_mm on the y, colore by species of penguins", fig.cap="Pengins by fiipper length vs bill length."}
ggplot(penguins, aes(x = bill_length_mm,
                     y = flipper_length_mm,
                     color = species)) +
  geom_point()
```


```{r}
#| message=FALSE,
#| warning=FALSE,
#| fig.alt="This is for a screen reader and this is a figure of the bill_length_mm on the x axis, and the fillter_lenth_mm on the y, colore by species of penguins",
#| fig.cap="Pengins by fiipper length vs bill length."

ggplot(penguins, aes(x = bill_length_mm,
                     y = flipper_length_mm,
                     color = species)) +
  geom_point() +
  geom_hline(yintercept = 205) +
  geom_vline(xintercept = 45)
```


```{r}
penguins %>%
  count(species, my_predict)
```

