name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: |
        Rscript -e "install.packages('docopt')"
        Rscript -e "install.packages('knitr')"
        Rscript -e "install.packages('tidyverse')"
        Rscript -e "install.packages('palmerpenguins')"
      

    - name: Render report
      run: make all


