name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    
    - name: Install packages
      run: |
        Rscript -e "install.packages("docopt", repos="http://cran.us.r-project.org")"
        Rscript -e "install.packages("gridExtra", repos="http://cran.us.r-project.org")"
        Rscript -e "install.packages("knitr", repos="http://cran.us.r-project.org")"
        Rscript -e "install.packages("tidyverse", repos="http://cran.us.r-project.org")"
        Rscript -e "install.packages("palmerpenguins", repos="http://cran.us.r-project.org")"

      

    - name: Render report
      run: make all


