name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
      with:
        profile: '"shiny"'
      
    - name: Activate and Install renv
      run: |
        Rscript -e "install.packages('renv')"
        Rscript -e "renv::restore()"
    

      

    - name: Render report
      run: make all


