name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
          extra-packages: any::covr
          needs: coverage

    - name: Render report
      run: make all


